query getDNAPageContent($name: String!, $url: String!) {
	DNA_content {
		status
		card_list(filter: { status: { _eq: "published" } }, sort: ["order"]) {
			title
			order
			icon {
				filename_disk
			}
			translations(filter: { languages_code: { name: { _eq: $name } } }) {
				title
				description
			}
		}
		RGPD_img {
			id
		}
		translations(filter: { languages_code: { name: { _eq: $name } } }) {
			title
			description
		}
	}
	meta_tags {
		page_tags(filter: { url: { _eq: $url } }) {
			url
			img {
				id
			}
			translations(filter: { languages_code: { name: { _eq: $name } } }) {
				title
				description
			}
		}
	}
}
