query getCaseStudyList($name: String!, $url: String!) {
	case_study_section {
		status
		id
		case_study_list {
			tags
			slug
			img {
				id
			}
			translations(filter: { languages_code: { name: { _eq: $name } } }) {
				title
				languages_code {
					name
				}
				content
			}
		}
	}

	meta_tags {
		page_tags(filter: { url: { _eq: $url } }) {
			url
			img {
				id
			}
			translations(filter: { languages_code: { name: { _eq: $name } } }) {
				title
				description
			}
		}
	}
}
